create database backend charset utf8;

USE backend;

CREATE TABLE stuInfo(
    ks_ID INT PRIMARY KEY AUTO_INCREMENT,
    yb_ID VARCHAR(10),
    stu_ID VARCHAR(12),
    NAME VARCHAR(20),
    institute_ID INT,
    class_ID INT,
    EMAIL VARCHAR(255),
    CREATETIME DATETIME,
    UPDATETIME DATETIME
);

CREATE TABLE instituteInfo(
    institute_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20),
    DESCRIPTION VARCHAR(255),
    leader_ID INT,
    STATE TINYINT(1),
    CREATETIME DATETIME,
    UPDATETIME DATETIME
);

CREATE TABLE classInfo(
    class_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(40),
    leader_ID INT,
    STATE TINYINT(1),
    stu_NUM INT,
    CREATETIME DATETIME,
    UPDATETIME DATETIME
);


CREATE TABLE teacherInfo(
    ks_ID INT PRIMARY KEY AUTO_INCREMENT,
    teacher_ID VARCHAR(12),
    yb_ID VARCHAR(10),
    NAME VARCHAR(20),
    EMAIL VARCHAR(255),
    PHONE CHAR(11),
    CREATETIME DATETIME,
    UPDATETIME DATETIME
);

CREATE TABLE dotInfo(
    dot_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(20),
    ks_ID INT,
    STATE TINYINT(1),
    TAGS VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    CREATETIME DATETIME,
    UPDATETIME DATETIME
);

CREATE TABLE draftInfo(
    draft_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(20),
    ks_ID INT,
    STATE TINYINT(1),
    TAGS VARCHAR(255),
    DESCRIPTION VARCHAR(255),
    CREATETIME DATETIME,
    UPDATETIME DATETIME
);

CREATE TABLE tagInfo(
    tag_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20),
    dot_NUM INT,
    leader_ID INT,
    CREATETIME DATETIME,
    UPDATETIME DATETIME
);

CREATE TABLE noteInfo(
    note_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(20),
    ks_ID INT,
    dot_ID INT,
    STATE TINYINT(1),
    CREATETIME DATETIME,
    UPDATETIME DATETIME
);